fn take_if_present(nul *buffer: [i32]) -> i32 {
    if *buffer is null {
        return 0
    } else {
        return unsafe raw_take buffer[0]
    }
}
fn main() -> i32 {
    auto *buffer# = unsafe alloc [1] i32
    unsafe { buffer[0] = 42 }
    auto value = take_if_present(*buffer)
    unsafe free [0] *buffer
    if value != 42 { return 1 }
    if take_if_present(null as nul *[i32]) != 0 { return 2 }
    return 0
}
