import std/vec::{Vec}
import core/option::{Option}

alias OptRefI32 = Option<&i32>

fn main() -> i32 {
    auto values# = Vec<i32>::new()
    values#.push(100)
    values#.push(200)

    auto sum# = 0:i32
    auto iter# = values.iter()
    auto done# = false:bool
    loop !done {
        auto item = iter#.next_ref()
        match item {
            auto OptRefI32::Some(&value) => {
                auto copied = value:i32
                sum += copied
            }
            auto OptRefI32::None => { done = true }
        }
    }

    if sum != 300 { return 1 }
    return 0
}
