import core/option::{Option}
import core/traits::{@Encap, @Iterable, @Iterator, @BorrowIterator}

pub shape Values(value: i32)

impl Values {
    pub fn set(self#, value: i32) {
        self.value = value
    }
}

pub shape ValuesCursor(
    &value: i32,
    done#: bool
)

impl ValuesCursor@Encap {
    pub value, done

    fn drop(self#) {}
}

impl ValuesCursor {
pub fn clone(self) -> ValuesCursor <- self {
        return ValuesCursor(&value = self.&value, done = self.done)
    }
}

impl Values@Iterable {
    type Iter = ValuesCursor

    pub fn iter(self) -> Iter <- self {
        return ValuesCursor(&value = &(self.value), done = false)
    }
}

impl ValuesCursor@Iterator {
    type Item = i32

    pub fn next(self#) -> Option<Item> {
        if self.done {
            return Option<Item>::None
        }
        self.done = true
        return Option<Item>::Some(self.value)
    }
}

impl ValuesCursor@BorrowIterator {
    type BorrowedItem = &i32

    pub fn next_ref(self#) -> Option<BorrowedItem> <- self {
        if self.done {
            return Option<BorrowedItem>::None
        }
        self.done = true
        return Option<BorrowedItem>::Some(&(self.value))
    }
}
