import core/traits::{@Encap}
import std/task::{block_on}

auto g_drop_count# = 0

shape Token(id: i32)

impl Token@Encap {
    fn drop(self#) {
        g_drop_count += 1
    }
}

impl Token {
    fn consume(cede self#) -> async i32 {
        self.id = 2
        auto owned = cede self
        return owned.id
    }
}

fn main() -> i32 {
    auto ^source# = new Token(id = 1)
    auto handle = source#.consume().start
    if block_on<i32>(handle) != 2 {
        return 1
    }
    return g_drop_count - 1
}
