import core/traits::{@Encap}

shape Token(value: i32)
impl Token@Encap { fn drop(self#) {} }
shape Runner()

impl Runner {
    fn static(cede left: Token, cede right: Token) -> async i32 {
        auto moved_left = cede left
        auto moved_right = cede right
        return moved_left.value + moved_right.value
    }
}

fn main() -> i32 {
    auto token = Token(value = 1:i32)
    auto task = Runner::static(token, token).start
    return token.value
}
