import core/traits::{@Encap}

shape Resource(value: i32)
shape Consumer()

impl Resource@Encap {
    fn drop(self#) {}
}

trait @Sink {
    fn combine(self, cede left: Resource, cede right: Resource) -> i32
}

impl Consumer@Sink {
    fn combine(self, cede left: Resource, cede right: Resource) -> i32 {
        auto moved_left = cede left
        auto moved_right = cede right
        return moved_left.value + moved_right.value
    }
}

fn invoke(sink: dyn @Sink, cede value: Resource) -> i32 {
    return sink.combine(value, value)
}

fn main() -> i32 {
    auto sink = Consumer()
    auto source = Resource(value = 1:i32)
    auto ignored = invoke(sink, source)
    return 0:i32
}
