import core/traits::{@Encap}

shape Resource(value: i32)

impl Resource@Encap {
    fn drop(self#) {}
}

fn consume(cede left: Resource, cede right: Resource) -> i32 {
    auto moved_left = cede left
    auto moved_right = cede right
    return moved_left.value + moved_right.value
}

fn main() -> i32 {
    auto source = Resource(value = 1:i32)
    auto ignored = consume(source, source)
    return source.value
}
