// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.

extern fn _NSGetArgc() -> *i32
extern fn _NSGetArgv() -> *Addr 

extern fn toka_opendir_impl(path: Addr) -> Addr
extern fn toka_readdir_impl(dir: Addr) -> Addr
extern fn toka_closedir_impl(dir: Addr) -> void
extern fn toka_readdir_name(entry: Addr) -> Addr

extern fn toka_stat_impl(path: Addr) -> Addr
extern fn toka_stat_mode(handle: Addr) -> u32
extern fn toka_stat_size(handle: Addr) -> u64
extern fn toka_stat_mtime(handle: Addr) -> i64
extern fn toka_stat_free(handle: Addr) -> void

extern fn toka_panic(*msg_ptr: char, len: i32) -> void
extern fn toka_get_last_error() -> i32
extern fn toka_set_errno_impl(err: i32) -> void

extern fn toka_rt_bind_with_diag(fd: i32, ip: u32, port: u16, *out_errno: i32, *out_sockaddr: u8) -> i32
extern fn toka_rt_listen_with_diag(fd: i32, backlog: i32, *out_errno: i32) -> i32
extern fn toka_rt_local_port_with_diag(fd: i32, *out_errno: i32) -> i32
extern fn toka_rt_local_addr_with_diag(fd: i32, *out_ip: u32, *out_port: u16, *out_errno: i32) -> i32
extern fn toka_rt_connect_with_diag(fd: i32, ip: u32, port: u16, *out_errno: i32) -> i32

extern fn bind(fd: i32, *addr: void, len: u32) -> i32
extern fn connect(fd: i32, *addr: void, len: u32) -> i32
extern fn accept(fd: i32, *addr: void, *len: u32) -> i32
extern fn listen(fd: i32, backlog: i32) -> i32
extern fn getsockopt(fd: i32, level: i32, optname: i32, *optval: void, *optlen: u32) -> i32
extern fn getsockname(fd: i32, *addr: void, *addrlen: u32) -> i32
extern fn libc_recv(fd: i32, *buf: void, len: usize, flags: i32) -> i64
extern fn libc_send(fd: i32, *buf: void, len: usize, flags: i32) -> i64
extern fn libc_recvfrom(fd: i32, *buf: void, len: usize, flags: i32, *src_addr: void, *addrlen: u32) -> i64
extern fn libc_sendto(fd: i32, *buf: void, len: usize, flags: i32, *dest_addr: void, addrlen: u32) -> i64

extern fn kqueue() -> i32
extern fn kevent(kq: i32, *changelist: void, nchanges: i32, *eventlist: void, nevents: i32, *timeout: void) -> i32
extern fn fcntl(fd: i32, cmd: i32, ...) -> i32
