#pragma once

#define TOKA_INTERFACE_FORMAT_VERSION "4"
#define TOKA_COMPILER_INTERFACE_VERSION "0.9.9-24"
#define TOKA_LOCAL_BODY_POLICY "checked-local-v1"
#define TOKA_PLACE_YIELD_ABI_SCHEMA_VERSION "1"
