#!/usr/bin/env python3
"""Observe only generated byte-buffer allocator/drop sites, not runtime malloc."""
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
SOURCE = '''import std/vec::{Vec}
import std/bytes::{Bytes}
import std/task::{block_on, __toka_spawn_blocking}
extern fn byte_test_live() -> i32
extern fn byte_test_allocations() -> i32
fn produce() -> async Bytes {
    auto value# = Vec<u8>::with_capacity(3)
    auto index# = 0:usize
    loop index < 71:usize { value#.push(index as u8); index += 1:usize }
    return Bytes::from_vec(cede value)
}
fn hold_bytes(cede value: Vec<u8>) -> async Vec<u8> { return cede value }
fn early() -> i32 {
    auto value = block_on(produce())
    assert(value.len() == 71:usize, "prepared result")
    return 0
}
fn main() -> i32 {
    assert(early() == 0, "early exit")
    assert(byte_test_live() == 0, "taken result released")
    {
        auto task = produce()
        __toka_spawn_blocking(task.*coro_handle)
        assert(byte_test_live() == 1, "completed result owned by task")
    }
    assert(byte_test_live() == 0, "unclaimed completed result released")
    {
        auto value# = Vec<u8>::with_capacity(9)
        value#.push(9:u8)
        auto task = hold_bytes(cede value)
    }
    assert(byte_test_live() == 0, "cold task input released")
    assert(byte_test_allocations() == 13, "only the required growth allocations")
    return 0
}
'''
OBSERVER = '''#include <stdlib.h>
#include <stdio.h>
static void *live[4096];
static int count, allocations;
void *byte_test_malloc(size_t size) {
    void *p = malloc(size);
    if (!p || count == 4096) abort();
    live[count++] = p;
    ++allocations;
    return p;
}
void byte_test_free(void *p) {
    if (!p) return;
    int i;
    for (i = 0; i < count && live[i] != p; ++i) {}
    if (i == count) { fputs("BYTE_UNOWNED_OR_DOUBLE_FREE\\n", stderr); abort(); }
    live[i] = live[--count];
    free(p);
}
int byte_test_live(void) { return count; }
int byte_test_allocations(void) { return allocations; }
'''


def run(build_dir):
    compiler = Path(build_dir).resolve() / 'bin/tokac'
    env = dict(os.environ, TOKA_LIB=str(ROOT / 'lib'))
    with tempfile.TemporaryDirectory(prefix='toka-byte-cleanup-') as directory:
        work = Path(directory)
        source, ir, observer = work / 'cleanup.tk', work / 'cleanup.ll', work / 'observer.c'
        source.write_text(SOURCE)
        observer.write_text(OBSERVER)
        emitted = subprocess.run([str(compiler), str(source), '--emit-llvm', '-o', str(ir)],
                                 cwd=ROOT, env=env, capture_output=True, text=True, timeout=90)
        assert emitted.returncode == 0, emitted.stderr
        text = ir.read_text()
        allocations = releases = 0

        def instrument(match):
            nonlocal allocations, releases
            name, body = match.group(1), match.group(0)
            if name in ('Vec_M_u8_with_capacity', 'Vec_M_u8_grow', 'Bytes_with_capacity'):
                allocations += body.count('call ptr @malloc(')
                body = body.replace('call ptr @malloc(', 'call ptr @byte_test_malloc(')
            if name in ('Vec_M_u8_grow', 'Encap_Vec_M_u8_drop', 'Encap_Bytes_drop'):
                releases += body.count('call void @free(')
                body = body.replace('call void @free(', 'call void @byte_test_free(')
            return body

        text = re.sub(r'^define [^\n]*@([^ (]+)\([^\n]*\{\n.*?^\}', instrument, text, flags=re.M | re.S)
        assert allocations >= 2 and releases >= 3, (allocations, releases)
        text += '\ndeclare ptr @byte_test_malloc(i64)\ndeclare void @byte_test_free(ptr)\n'
        ir.write_text(text)
        executable = work / 'cleanup'
        linked = subprocess.run(['clang', str(ir), str(observer), str(ROOT / 'lib/sys/toka_rt.c'),
                                 '-pthread', '-lm', '-o', str(executable)],
                                capture_output=True, text=True, timeout=60)
        assert linked.returncode == 0, linked.stderr
        result = subprocess.run([str(executable)], capture_output=True, text=True, timeout=30)
        assert result.returncode == 0, (result.returncode, result.stdout, result.stderr)
        print('PASS byte allocation cleanup: growth, taken/unclaimed result, cold task and early exit', flush=True)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--build-dir', required=True)
    run(parser.parse_args().build_dir)
