trait @Producer {
    type Item
    fn relay(self, cede value:Item) -> Item
}
shape Provider<T>(marker:bool)
impl<T> Provider<T>@Producer {
    type Item = T
    fn relay(self, cede value:Item) -> Item { return cede value }
}
shape Resource(value:i32)
fn through_method<T>(provider:Provider<T>, cede value:T) -> T {
    auto result = provider.relay(cede value)
    return cede result
}
fn main() -> i32 {
    auto provider = Provider<^Resource>(marker=true)
    auto ^owner = new Resource(value=7)
    auto ^result = through_method<^Resource>(provider, cede ^owner)
    if result.value != 7 { return 1 }
    return 0
}
