shape View(text:str)
fn forward<T>(value:T) -> &T <- value { return &value }
fn main() -> i32 {
    auto left = string::from_str("left")
    auto right = string::from_str("right")
    auto first = View(text=left.as_str())
    auto second = View(text=right.as_str())
    auto &a = forward<View>(first)
    auto &b = forward(second)
    if a.text != "left" || b.text != "right" { return 1 }
    return 0
}
