auto drops# = 0:i32
shape Resource(value:i32)
impl Resource@Encap {
    pub value
    fn drop(self#) { drops += 1 }
}
shape Box<T>(value:T)
fn relay_box<T>(cede box:Box<T>) -> Box<T> { return cede box }
fn inspect<T>(&value:T) {}
fn wrap<T>(cede value:T) -> Box<T> {
    auto initial = Box<T>(value=cede value)
    auto result = relay_box(cede initial)
    inspect<T>(&(result.value))
    return cede result
}
fn main() -> i32 {
    {
        auto ^owner = new Resource(value=31)
        auto result = wrap<^Resource>(cede ^owner)
        if result.value.value != 31 { return 1 }
    }
    return drops - 1
}
