import core/str::{str}

pub shape TokenKind(
    Unknown |
    Identifier |
    Number |
    StringLit |
    CharLit |
    Keyword |
    Operator |
    Delimiter |
    Whitespace |
    Comment |
    EOF
)

pub shape Token (
    kind: TokenKind,
    lexeme_addr: Addr,
    lexeme_len: usize,
    line: i32,
    col: i32
)

impl Token {
    pub fn new(kind: TokenKind, lexeme_addr: Addr, lexeme_len: usize, line: i32, col: i32) -> Token {
        return Token(
            kind = kind,
            lexeme_addr = lexeme_addr,
            lexeme_len = lexeme_len,
            line = line,
            col = col
        )
    }

    pub fn lexeme(self) -> str <- self {
        unsafe {
            return str(&buf = (self.lexeme_addr as *[char]) as &[char], len = self.lexeme_len)
        }
    }
}
