import ./lib::{Token}

fn main() -> i32 {
    auto drops# = 0
    {
        auto i# = 0
        auto values: [Token; 2] = [Token(id = 1, &drops = &drops), Token(id = 2, &drops = &drops)]
        loop i < 1 {
            auto taken = cede values[0]
            if taken.id != 1 { return 1 }
            i += 1
        }
        if values[1].id != 2 { return 2 }
    }
    if drops != 2 { return 3 }
    return 0
}
