pub shape WildcardBox (
    open_val: i32,
    secret_val: i32
)

impl WildcardBox@encap {
    pub open_val

    fn drop(self#) {}
}

impl WildcardBox {
    pub fn new(open_val: i32, secret_val: i32) -> WildcardBox {
        return WildcardBox(open_val = open_val, secret_val = secret_val)
    }

    pub fn clone(self) -> WildcardBox {
        return WildcardBox(open_val = self.open_val, secret_val = self.secret_val)
    }
}

pub shape PathBox (
    path_val: i32,
    private_val: i32
)

impl PathBox@encap {
    pub path_val

    fn drop(self#) {}
}

impl PathBox {
    pub fn new(path_val: i32, private_val: i32) -> PathBox {
        return PathBox(path_val = path_val, private_val = private_val)
    }

    pub fn clone(self) -> PathBox {
        return PathBox(path_val = self.path_val, private_val = self.private_val)
    }
}

pub shape CrateBox (
    crate_val: i32,
    private_val: i32
)

impl CrateBox@encap {
    pub crate_val

    fn drop(self#) {}
}

impl CrateBox {
    pub fn new(crate_val: i32, private_val: i32) -> CrateBox {
        return CrateBox(crate_val = crate_val, private_val = private_val)
    }

    pub fn clone(self) -> CrateBox {
        return CrateBox(crate_val = self.crate_val, private_val = self.private_val)
    }
}
