import core/option::{Option}

shape Cursor(pos#: i32)

impl Cursor {
    pub fn next(self#) -> Option<i32> {
        if self.pos > 0 {
            return Option<i32>::None
        }
        self.pos += 1
        return Option<i32>::Some(1)
    }
}

shape Values()

impl Values {
    pub fn iter(self) -> Cursor <- self {
        return Cursor(pos = 0)
    }
}

pub fn main() -> i32 {
    auto values = Values()
    for auto value in values {
        if value == 2 {
            return 1
        }
    }
    return 0
}
