import core/option::{Option}
import core/traits::{@Iterable, @Iterator}

shape Cursor(pos#: i32)

impl Cursor@Iterator {
    type Item = i32

    pub fn next(self#) -> Option<Item> {
        if self.pos > 0 {
            return Option<Item>::None
        }
        self.pos += 1
        return Option<Item>::Some(1)
    }
}

shape Values()

impl Values@Iterable {
    type Iter = Cursor

    pub fn iter(self) -> Iter {
        return Cursor(pos = 0)
    }
}

pub fn main() -> i32 {
    auto values = Values()
    for auto value in values {
        if value == -1 {
            return 1
        }
    }
    return 0
}
