import stdx/serde/json_factory::{@JsonFactory}
import std/vec::{Vec}
fn main() -> i32 {
    auto number = i32::parse_value("42tail").unwrap()
    if number.value != 42 || !number.rest.equals("tail") { return 1 }
    auto empty_result = Option<i32>::parse_value("null!").unwrap()
    if !empty_result.value.is_none() || !empty_result.rest.equals("!") { return 2 }
    auto present_result = Option<i32>::parse_value("42!").unwrap()
    if present_result.value.unwrap() != 42 || !present_result.rest.equals("!") { return 3 }
    auto list_result = Vec<i32>::parse_value("[1, 2, 3]!").unwrap()
    if list_result.value.len() != 3 || !list_result.rest.equals("!") { return 4 }
    return 0
}
