trait @Sink {
    fn combine(self, cede left: i32, cede right: i32) -> i32
    fn inspect(self, value: i32) -> i32
}

shape IntSink()

impl IntSink@Sink {
    fn combine(self, cede left: i32, cede right: i32) -> i32 {
        auto lhs = cede left
        auto rhs = cede right
        return lhs + rhs
    }

    fn inspect(self, value: i32) -> i32 {
        return value
    }
}

fn invoke(sink: dyn @Sink) -> i32 {
    auto first = 1:i32
    auto second = 2:i32
    auto result = sink.combine(cede first, second)
    return sink.inspect(first) + sink.inspect(second) + result
}

fn main() -> i32 {
    auto sink = IntSink()
    return invoke(sink)
}
