trait @Sink {
    fn inspect(self, value: i32) -> i32
    fn take(self, cede value: i32) -> i32
}

shape IntSink()

impl IntSink@Sink {
    fn inspect(self, value: i32) -> i32 {
        return value
    }

    fn take(self, cede value: i32) -> i32 {
        return cede value
    }
}

fn invoke(sink: dyn @Sink) -> i32 {
    auto value = 7:i32
    auto observed = sink.inspect(value)
    auto temporary = sink.take(1:i32)
    return observed + value + temporary - 15:i32
}

fn main() -> i32 {
    auto sink = IntSink()
    return invoke(sink)
}
