trait @Sink {
    fn take(self, cede value: i32) -> i32
}

shape IntSink()

impl IntSink@Sink {
    fn take(self, cede value: i32) -> i32 {
        return cede value
    }
}

fn invoke(sink: dyn @Sink) -> i32 {
    auto value = 7:i32
    auto moved = sink.take(cede unsafe value)
    auto temporary = sink.take(unsafe 1:i32)
    return moved + temporary - 8:i32
}

fn main() -> i32 {
    auto sink = IntSink()
    return invoke(sink)
}
