// EXPECT_TKI: return.first <- e1.val
// EXPECT_TKI: return.second <- e2.val
pub shape Engine(val: i32)

pub fn split_engines(e1: Engine, e2: Engine) -> res: (first: &i32, second: &i32)
effects:
    res.first <- e1.val
    res.second <- e2.val
{
    return (first = &(e1.val), second = &(e2.val))
}

pub fn split_swapped(e1: Engine, e2: Engine) -> res: (first: &i32, second: &i32)
effects:
    res.first <- e2.val
    res.second <- e1.val
{
    return (first = &(e2.val), second = &(e1.val))
}
