shape Refs(&left: i32, &right: i32)
fn pair(input: Refs) -> result: (left: &i32, right: &i32)
effects:
    result.left <- input
    result.right <- input
{
    return (left = input.&left, right = input.&right)
}
fn main() -> i32 {
    auto a = 3
    auto b = 5
    auto refs = Refs(&left = &a, &right = &b)
    auto result = pair(refs)
    if result.left != 3 { return 1 }
    if result.right != 5 { return 2 }
    return 0
}
