shape Token(lexeme: str, line: i32)

impl Token {
    fn new(lexeme: str, line: i32) -> Token <- lexeme {
        auto result = Token(lexeme = lexeme, line = line)
        return cede result
    }
}

shape Lexer(source: str, pos#: usize, line#: i32, col#: i32)

impl Lexer {
    fn next(self#) -> Token <- self {
        self.pos = self.pos + 1:usize
        self.line = self.line + 1
        self.col = self.col + 1
        auto ws = self.source.substring(0:usize, self.pos)
        self.col = self.col + 1
        auto result = Token::new(ws, self.line)
        return cede result
    }
}

fn main() -> i32 {
    auto source = " abc"
    auto lexer# = Lexer(source = source, pos = 0:usize, line = 0, col = 0)
    auto token = lexer#.next()
    if !token.lexeme.equals(" ") { return 1 }
    auto original = source.raw_ptr() as Addr
    auto actual = token.lexeme.raw_ptr() as Addr
    if actual != original { return 2 }
    if token.line != 1 { return 3 }
    return 0
}
