shape Holder(view: str)
impl Holder@Encap { pub view }
impl Holder {
    fn make(view: str) -> Holder <- view {
        auto result = Holder(view = view)
        return cede result
    }
}
fn main() -> i32 {
    auto literal = "static"
    auto copied = literal
    auto direct = Holder(view = copied)
    auto factory = Holder::make(copied)
    if !direct.view.equals(factory.view) { return 1 }
    return 0
}
