shape RawHolder(*address: i32)
shape Box<T>(value: T)
shape Mixed(view: str, nested: Box<Box<RawHolder>>)
fn factory(view: str, *address: i32) -> Mixed <- view {
    auto result = Mixed(view = view, nested = Box<Box<RawHolder>>(value = Box<RawHolder>(value = RawHolder(*address = *address))))
    return cede result
}
fn main() -> i32 {
    auto value = 1
    auto result = factory("static", &value as *i32)
    return 0
}
