// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import core/types::{char, str}

extern fn toka_panic(*msg: char, len: i32) -> void
extern fn __toka_str_raw_ptr(s: str) -> *char

pub fn __toka_panic_handler(msg: str) -> never {
    unsafe { toka_panic(__toka_str_raw_ptr(msg), msg.len as i32) }
    unreachable
}
