import core/option::{Option}

pub shape Cell(value: i32)

pub shape Holder(
    ~cell#: Cell
)

pub shape ReadonlyHolder(
    ~cell: Cell
)

pub fn overwrite(~p#: Cell) -> i32 {
    p.value = 12
    return 0
}

// EXPECT_TKI: pub fn cede_overwrite(cede ~p#: Cell) -> i32
pub fn cede_overwrite(cede ~p#: Cell) -> i32 {
    p.value = 13
    auto ~consumed = cede ~p
    return consumed.value
}

pub fn generic_overwrite<T>(~p#: T) -> i32 {
    return 0
}

pub shape CallableMutator()

impl CallableMutator@Callable {
    fn call(self, value#: Cell) -> i32 {
        value.value = 13
        return 0
    }
}

// EXPECT_TKI: pub shape ReadonlyRefBox(&slot: i32)
pub shape ReadonlyRefBox(
    &slot: i32
)

// EXPECT_TKI: pub shape WritableRefBox(&slot#: i32)
pub shape WritableRefBox(
    &slot#: i32
)

pub fn expose(~p#: Cell) -> ~Cell# {
    return ~p
}

// EXPECT_TKI: pub fn writable_option(p#: i32) -> Option<&i32#>
pub fn writable_option(p#: i32) -> Option<&i32#> {
    return Option<&i32#>::Some(&p)
}

// EXPECT_TKI: pub fn readonly_option(p: i32) -> Option<&i32>
pub fn readonly_option(p: i32) -> Option<&i32> {
    return Option<&i32>::None
}
