import core/string::{string}
import core/option::{Option}

fn choose() -> string {
    auto newest# = string::from("old")
    auto option = Option<string>::Some(string::from("new"))
    match cede option {
        auto Option<string>::Some(entry) => { newest = cede entry }
        Option<string>::None => {}
    }
    return cede newest
}

fn main() -> i32 {
    auto result = choose()
    if !result.as_str().equals("new") { return 1 }
    return 0
}
