import std/vec::{Vec}
import core/string::{string}

fn independent() -> Vec<str> {
    auto owner = string::from("local")
    auto left# = Vec<str>::new()
    left#.push(owner.as_str())
    auto right# = Vec<str>::new()
    right#.push("static")
    left = cede right
    return cede left
}

fn main() -> i32 {
    auto values = independent()
    if !values.borrow(0:usize).equals("static") { return 1 }
    return 0
}
