import std/vec::{Vec}

fn extract(owner: string) -> str <- owner {
    auto values# = Vec<str>::new()
    values#.push(owner.as_str())
    auto result = values#.pop()
    return result.unwrap()
}

fn main() -> i32 {
    auto owner# = string::from("stable")
    {
        auto view = extract(owner)
        if !view.equals("stable") { return 1 }
    }
    owner#.push_str("!")
    if !owner.as_str().equals("stable!") { return 2 }
    return 0
}
