// EXPECT_TKI: pub shape Cell(value: i32)
// EXPECT_TKI: pub fn consume(cede cell: Cell) -> i32
// EXPECT_TKI: pub fn consume_static(cede cell: Cell) -> i32
// EXPECT_TKI: pub fn take(cede self
pub shape Cell(value: i32)

pub fn consume(cede cell: Cell) -> i32 {
    auto owned = cede cell
    return owned.value
}

impl Cell {
    pub fn consume_static(cede cell: Cell) -> i32 {
        auto owned = cede cell
        return owned.value
    }
}

impl Cell {
    pub fn take(cede self) -> i32 {
        auto owned = cede self
        return owned.value
    }
}
