// EXPECT_TKI: pub shape Cell(value: i32)
// EXPECT_TKI: pub fn consume(cede cell: Cell) -> i32
// EXPECT_TKI: pub fn consume_static(cede cell: Cell) -> i32
// EXPECT_TKI: pub fn take(cede self
// EXPECT_TKI: pub fn take_mut(cede self#: Cell) -> cede Cell
// EXPECT_TKI: pub fn mutate_unique_parameter(cede ^cell#: Cell) -> i32
// EXPECT_TKI: pub fn mutate_async_unique_parameter(cede ^cell#: Cell) -> async i32
pub shape Cell(value: i32)

pub fn consume(cede cell: Cell) -> i32 {
    auto owned = cede cell
    return owned.value
}

pub fn mutate_unique_parameter(cede ^cell#: Cell) -> i32 {
    cell.value = 11
    auto ^owned = cede ^cell
    return owned.value
}

pub fn mutate_async_unique_parameter(cede ^cell#: Cell) -> async i32 {
    cell.value = 12
    auto ^owned = cede ^cell
    return owned.value
}

impl Cell {
    pub fn consume_static(cede cell: Cell) -> i32 {
        auto owned = cede cell
        return owned.value
    }
}

impl Cell {
    pub fn take(cede self) -> i32 {
        auto owned = cede self
        return owned.value
    }

    pub fn take_mut(cede self#) -> cede Cell {
        self.value = 13
        return cede self
    }
}
