import std/hashmap::{Entry}
extern fn run_raw_probe() -> i32
pub fn raw_probe(*key: [*i32], *val: i32) -> i32 {
    auto entry = unsafe Entry<*i32, i32>(*key = (*key as **i32), *val = *val)
    auto **k = entry.key()
    auto *v = entry.val()
    if k != 5 || v != 9 { return 1 }
    return 0
}
fn main() -> i32 {
    auto key = 5:i32
    auto val = 9:i32
    auto *key_ptr = unsafe (&key as *i32)
    auto *val_ptr = unsafe (&val as *i32)
    auto entry = Entry<i32, i32>(*key = *key_ptr, *val = *val_ptr)
    auto *k = entry.key()
    auto *v = entry.val()
    if k != 5 || v != 9 { return 2 }
    return run_raw_probe()
}
