// EXPECT_TKI: pub alias Int = i32
// EXPECT_TKI: pub fn test_unique(&^x: i32) -> i32
// EXPECT_TKI: pub fn test_shared(&~x: i32) -> i32
// EXPECT_TKI: pub fn test_ref(&&x: i32) -> i32
// EXPECT_TKI: pub fn test_alias_unique(&^x: Int) -> i32
// EXPECT_TKI: pub fn test_alias_shared(&~x: Int) -> i32
// EXPECT_TKI: pub fn test_alias_ref(&&x: Int) -> i32
// EXPECT_TKI_ROUNDTRIP

pub alias Int = i32

pub fn test_unique(&^x: i32) -> i32 {
    return x
}

pub fn test_shared(&~x: i32) -> i32 {
    return x
}

pub fn test_ref(&&x: i32) -> i32 {
    return x
}

pub fn test_alias_unique(&^x: Int) -> i32 {
    return x
}

pub fn test_alias_shared(&~x: Int) -> i32 {
    return x
}

pub fn test_alias_ref(&&x: Int) -> i32 {
    return x
}
