import sys/thread::{sys_alloc_thread_env, sys_free_thread_env}
import sys/libc::{libc_abort}
fn unsafe_checked<'T>(address: Addr) -> *'T# {
    auto nul *candidate# = unsafe (address as nul *'T#)
    if *candidate is null {
        unsafe { libc_abort() }
        unreachable
    } else {
        auto verified = unsafe *candidate as Addr
        return unsafe (verified as *'T#)
    }
}
fn main() -> i32 {
    auto address = sys_alloc_thread_env(sizeof(i32) as usize)
    auto *writer# = unsafe_checked<[i32]>(address)
    unsafe {
        writer[0] = 42:i32
        if writer[0] != 42 { return 1 }
    }
    sys_free_thread_env(address)
    return 0
}
