import std/thread::{thread_spawn}

shape SyncToken(value: i32)
impl SyncToken@Send {}
impl SyncToken@Sync {}
impl SyncToken {
    fn id(self) -> i32 { return self.value }
}

fn main() -> i32 {
    auto token = SyncToken(value = 42)
    auto callback = { [copy token] => token.id() }
    auto spawned = thread_spawn<i32>(cede callback)
    if spawned.is_err() { return 1 }
    auto handle# = spawned.unwrap()
    auto result = handle#.join()
    if result.is_err() { return 2 }
    if result.unwrap() != 42 { return 3 }
    if token.id() != 42 { return 4 }
    return 0
}
