shape Cell(value#: i32)

fn overwrite(^p#: Cell) {
    p.value = 9
}

fn reset(^#p: Cell) {
    ^p = new Cell(value = 8)
}

fn overwrite_value(value#: i32) {
    value = 4
}

fn main() -> i32 {
    auto ^payload_only# = new Cell(value = 1)
    overwrite(^payload_only)
    if payload_only.value != 9 { return 1 }

    auto ^#handle_only = new Cell(value = 1)
    reset(^#handle_only)
    if handle_only.value != 8 { return 2 }

    auto value# = 1
    overwrite_value(value)
    if value != 4 { return 3 }
    return 0
}
