import core/traits::{@Encap}

auto g_drop_count# = 0

shape Token(id: i32)

impl Token@Encap {
    fn drop(self#) {
        g_drop_count += 1
    }
}

fn main() -> i32 {
    {
        auto values = [Token(id = 1), Token(id = 2)]:[Token; 2]
        auto &borrow = &(values[0])
        auto taken = cede values[1]
        if borrow.id != 1 { return 1 }
        if taken.id != 2 { return 2 }
    }
    return g_drop_count - 2
}
