shape Token(id: i32)
shape Consumer()

impl Consumer@Callable {
    fn call(self, cede token: Token) -> i32 {
        auto owned = cede token
        return owned.id
    }
}

fn main() -> i32 {
    auto consumer = Consumer()
    auto ^source#: Token? = new Token(id = 8)
    auto result# = 0
    guard source {
        result = consumer(cede source)
    } else {
        result = -1
    }
    if result != 8 {
        return 1
    }
    return 0
}
