#!/usr/bin/env python3

"""Regenerate the deterministic 5K+ Toka telemetry pipeline fixture."""

import argparse
from pathlib import Path


MODULE_COUNT = 20
RULES_PER_MODULE = 24


def module_source(module_index):
    module = "%02d" % module_index
    parts = [
        "// Generated by generate.py; models one telemetry scoring stage.",
    ]
    if module_index:
        previous = "%02d" % (module_index - 1)
        parts.extend([
            "import ./stage_%s::{stage_%s}" % (previous, previous),
            "",
        ])
    parts.extend([
        "pub shape Reading%s (" % module,
        "    value: i32,",
        "    quality: i32",
        ")",
        "",
    ])
    for rule_index in range(RULES_PER_MODULE):
        rule = "%02d" % rule_index
        adjustment = (module_index * 7 + rule_index * 3) % 11
        parts.extend([
            "/// Deterministic calibration rule %s for stage %s." %
            (rule, module),
            "pub fn calibrate_%s_%s(value: i32) -> i32 {" % (module, rule),
            "    auto calibrated = value + %d" % adjustment,
            "    if calibrated < 0 {",
            "        return 0",
            "    }",
            "    if calibrated > 1000000 {",
            "        return 1000000",
            "    }",
            "    return calibrated",
            "}",
            "",
        ])
    prior = ("value" if module_index == 0 else
             "stage_%02d(value)" % (module_index - 1))
    parts.extend([
        "/// Run this stage after all upstream telemetry stages.",
        "pub fn stage_%s(value: i32) -> i32 {" % module,
        "    auto upstream = %s" % prior,
        "    return calibrate_%s_00(upstream)" % module,
        "}",
        "",
    ])
    return "\n".join(parts)


def generate(destination):
    destination.mkdir(parents=True, exist_ok=True)
    expected = set()
    for module_index in range(MODULE_COUNT):
        path = destination / ("stage_%02d.tk" % module_index)
        path.write_text(module_source(module_index), encoding="utf-8")
        expected.add(path.name)
    final = MODULE_COUNT - 1
    main = destination / "main.tk"
    main.write_text(
        "// Reference entry point for the telemetry scoring pipeline.\n"
        "import ./stage_%02d::{stage_%02d}\n\n" % (final, final) +
        "fn main() -> i32 {\n"
        "    return stage_%02d(1)\n" % final +
        "}\n",
        encoding="utf-8",
    )
    expected.add(main.name)
    for path in destination.glob("*.tk"):
        if path.name not in expected:
            path.unlink()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "destination", nargs="?",
        default=str(Path(__file__).resolve().parent / "src"),
    )
    args = parser.parse_args()
    generate(Path(args.destination).resolve())


if __name__ == "__main__":
    main()
