
import sys/libc::{libc_printf, libc_abort}

impl<'T> Option<'T> {
    /// Unwrap the option or panic with a custom error message
    pub fn expect(cede self, *msg: char) -> 'T <- self {
        match cede self {
            auto Option<'T>::Some('val) => return 'val
            _ => {
                unsafe {
                    libc_printf(c"[Option] panic: %s\n", msg)
                    libc_abort()
                }
                unreachable
            }
        }
    }
}

impl<'T, 'E> Result<'T, 'E> {
    /// Unwrap the result or panic with a custom error message
    pub fn expect(cede self, *msg: char) -> 'T <- self {
        match cede self {
            auto Result<'T, 'E>::Ok('val) => return 'val
            _ => {
                unsafe {
                    libc_printf(c"[Result] panic: %s\n", msg)
                    libc_abort()
                }
                unreachable
            }
        }
    }
    
    /// Unwrap the error or panic with a custom error message
    pub fn expect_err(cede self, *msg: char) -> 'E <- self {
        match cede self {
            auto Result<'T, 'E>::Err('val) => return 'val
            _ => {
                unsafe {
                    libc_printf(c"[Result] panic: %s\n", msg)
                    libc_abort()
                }
                unreachable
            }
        }
    }
}
