import core/string::{string}
import core/option::{Option}

shape Resource(name: string)
impl Resource@Encap {
    fn drop(self#) {}
}

fn main() -> i32 {
    auto opt = Option<Resource>::Some(Resource(name = string::from("hello")))
    match opt {
        auto Option<Resource>::Some('val) => {
            auto stolen = cede 'val
        }
        auto Option<Resource>::None => {}
    }
    return 0
}
