import core/string::{string}
import core/option::{Option}

shape Resource(name: string)
impl Resource@Encap {
    fn drop(self#) {}
}

fn test_match_return() -> Resource {
    auto opt = Option<Resource>::Some(Resource(name = string::from("hello")))
    match opt {
        auto Option<Resource>::Some('val) => return 'val
        auto Option<Resource>::None => return Resource(name = string::from("fallback"))
    }
}

fn main() -> i32 {
    return 0
}
