import std/io::println

fn main() -> i32 {
    auto outer_cnt# = 0
    auto inner_cnt# = 0

    auto outer = loop {
        outer_cnt += 1
        println("Outer loop iteration")

        auto inner = loop {
            inner_cnt += 1
            println("Inner loop iteration")

            if inner_cnt == 3 {
                // Break all the way out to outer
                break to outer
            }
        }:()
    }:()
    println("Finished nested loop. outer_cnt: {}, inner_cnt: {}", outer_cnt, inner_cnt)
    assert(outer_cnt == 1, "outer_cnt should be 1")
    assert(inner_cnt == 3, "inner_cnt should be 3")

    return 0
}
