// unset_init.tk
import std/io::println

shape Point(
    x: i32,
    y: i32
)

fn main() -> i32 {
    // Case 1: explicit construction of the whole place
    auto p = uninit:Point
    init p = Point(x = 10, y = 20)

    println("p.x: {}", p.x)
    assert(p.x == 10, "p.x check")
    
    // Case 2: use a reference only after whole-place construction
    auto q = uninit:i32
    init q = 100
    auto &refQ# = &q

    // Using reference in Pass/If
    auto val = if true {
        pass refQ // OK because refQ is clean
    } else {
        pass refQ
    }:i32

    assert(val == 100, "val check")
    
    return 0
}
