import std/io::{println}
import stdx/serde/json::{deserialize_shape}
import core/str::{str}

shape UniTest (
    msg: string = string(..)
)

fn main() -> i32 {
    auto json_str = string::from("{\"msg\": \"hello\\n\\t\\\"world\\\"\\u1f68\\uD83D\\uDE80\"}")
    auto v_str = json_str.as_str()
    
    auto res = deserialize_shape<UniTest>(v_str)
    if res.is_err() {
        println("Parse err")
        return 1
    }
    
    auto obj# = res.unwrap()
    auto decoded_msg = obj.msg.as_str()
    // It should be: "hello\n\t\"world\"" followed by \u1f68 then rocket (F0 9F 9A 80)
    
    // Check length or characters
    if decoded_msg.byte_at(5:usize) != 10 { return 2 } // \n
    if decoded_msg.byte_at(6:usize) != 9 { return 3 }  // \t
    if decoded_msg.byte_at(7:usize) != 34 { return 4 } // "
    
    println("All unicode matches OK!")
    return 0
}
import stdx/serde/json::{@JsonFactory, Parsed, parse_document}
impl UniTest@JsonFactory {
    pub fn parse_value(input: str) -> Result<Parsed<UniTest>, str> <- input {
        auto attempt = parse_document(input)
        if attempt.is_err() {
            auto error = Result<Parsed<UniTest>, str>::Err("Invalid JSON")
            return cede error
        }
        auto document = attempt.unwrap()
        if document.kind(1) != 5 {
            auto error = Result<Parsed<UniTest>, str>::Err("Expected object")
            return cede error
        }
        if document.kind(document.find(1, "msg")) != 3 {
            auto error = Result<Parsed<UniTest>, str>::Err("Invalid field msg")
            return cede error
        }
        auto value = UniTest(msg = string::from(document.text(document.find(1, "msg"))))
        auto parsed = Parsed<UniTest>(value = cede value, rest = input.substr(input.len(), 0))
        auto result = Result<Parsed<UniTest>, str>::Ok(cede parsed)
        return cede result
    }
}
