import std/io::{println}
import stdx/serde/json::{deserialize_shape}
import core/str::{str}

shape SciTest (
    a: f64 = 0.0,
    b: f64 = 0.0,
    c: f64 = 0.0,
    d: f64 = 0.0
)

fn main() -> i32 {
    // 1.2e-4, 3E10, -0.0, -4.56e2
    auto json_str = string::from("{\"a\": 1.2e-4, \"b\": 3E10, \"c\": -0.0, \"d\": -4.56e2}")
    auto v_str = json_str.as_str()
    
    auto res = deserialize_shape<SciTest>(v_str)
    if res.is_err() {
        println("Parse err")
        return 1
    }
    
    auto obj = res.unwrap()
    auto eps = 0.00000001
    
    auto diff_a# = obj.a - 0.00012
    if diff_a < 0.0 { diff_a = -diff_a }
    if diff_a > eps { return 1 }
    
    auto diff_b# = obj.b - 30000000000.0
    if diff_b < 0.0 { diff_b = -diff_b }
    if diff_b > eps { return 2 }
    
    if obj.c != 0.0 { return 3 } // -0.0 == 0.0
    
    auto diff_d# = obj.d + 456.0
    if diff_d < 0.0 { diff_d = -diff_d }
    if diff_d > eps { return 4 }

    println("All float matches OK!")
    return 0
}
import stdx/serde/json::{@JsonFactory, Parsed, parse_document}
impl SciTest@JsonFactory {
    pub fn parse_value(input: str) -> Result<Parsed<SciTest>, str> <- input {
        auto attempt = parse_document(input)
        if attempt.is_err() {
            auto error = Result<Parsed<SciTest>, str>::Err("Invalid JSON")
            return cede error
        }
        auto document = attempt.unwrap()
        if document.kind(1) != 5 {
            auto error = Result<Parsed<SciTest>, str>::Err("Expected object")
            return cede error
        }
        if document.kind(document.find(1, "a")) != 2 {
            auto error = Result<Parsed<SciTest>, str>::Err("Invalid field a")
            return cede error
        }
        if document.kind(document.find(1, "b")) != 2 {
            auto error = Result<Parsed<SciTest>, str>::Err("Invalid field b")
            return cede error
        }
        if document.kind(document.find(1, "c")) != 2 {
            auto error = Result<Parsed<SciTest>, str>::Err("Invalid field c")
            return cede error
        }
        if document.kind(document.find(1, "d")) != 2 {
            auto error = Result<Parsed<SciTest>, str>::Err("Invalid field d")
            return cede error
        }
        auto value = SciTest(a = document.number(document.find(1, "a")).unwrap(), b = document.number(document.find(1, "b")).unwrap(), c = document.number(document.find(1, "c")).unwrap(), d = document.number(document.find(1, "d")).unwrap())
        auto parsed = Parsed<SciTest>(value = cede value, rest = input.substr(input.len(), 0))
        auto result = Result<Parsed<SciTest>, str>::Ok(cede parsed)
        return cede result
    }
}
