
import std/io::println
import core/traits::{@Encap}

shape Node<T>(
    val: T,
    nul ^next: Node<T>
)
impl<T> Node<T>@Encap {
    pub val
    fn drop(self#) {
        println("dropping {}", self.val)
    }
}

fn main() -> i32 {
    {
        auto ^node222 = new Node<i32>(val = 222, ^next = null)
        assert(node222.val == 222, "unique Node factory")
    }
    {
        auto ^head = new Node<i32>(val = 0, ^next = null)
        auto ^next = cede ^head
        auto ^list = new Node<i32>(val = 1, ^next = cede ^next)
        assert(list.val == 1, "linked Node head")
    }
    println("End of main")
    return 0
}
