fn alloc_in_function<T>(value: T) -> T {
    unsafe {
        auto *ptr = unsafe alloc T(value)
        auto result = ptr
        free *ptr
        return result
    }
}

shape Allocator<T>()

impl<T> Allocator<T> {
    fn alloc_in_impl(self, value: T) -> T {
        unsafe {
            auto *ptr = unsafe alloc T(value)
            auto result = ptr
            free *ptr
            return result
        }
    }
}

fn main() -> i32 {
    if alloc_in_function<i32>(41) != 41 {
        return 1
    }

    auto allocator = Allocator<u64>()
    if allocator.alloc_in_impl(42) != 42 {
        return 2
    }
    return 0
}
