import std/channel::{channel, Sender, Receiver}
import std/vec::{Vec}
import core/result::{Result}
import std/error::{Error}
import std/thread::{thread_spawn, JoinHandle, sleep_ms}
import std/io::{println}

pub fn main() -> i32 {
    auto pair# = channel<i32>()
    auto t1_tx# = pair.tx#.clone()
    auto t2_tx# = pair.tx#.clone()
    
    // Thread 1
    auto task1 = { [cede t1_tx] =>
        auto sender# = cede t1_tx
        sleep_ms(10:u32)
        sender#.send(100).unwrap()
        return 0
    }
    auto t1# = thread_spawn<i32>(cede task1).unwrap()
    
    // Thread 2
    auto task2 = { [cede t2_tx] =>
        auto sender# = cede t2_tx
        sleep_ms(20:u32)
        sender#.send(200).unwrap()
        return 0
    }
    auto t2# = thread_spawn<i32>(cede task2).unwrap()
    
    // Receiver on Main Thread
    auto count# = 0
    auto sum# = 0
    
    loop count < 2 {
        auto res_opt = pair.rx#.recv()
        auto opt = res_opt.unwrap()
        auto val = opt.unwrap()
        sum = sum + val
        count = count + 1
    }
    
    println("Total received sum from 2 threads: {}", sum)
    if sum != 300 {
        return 3
    }

    assert(t1#.join().unwrap() == 0, "first sender completed")
    assert(t2#.join().unwrap() == 0, "second sender completed")
    
    return 0
}
