import core/result::{Result}
import core/traits::{ @Encap }
import core/types::{ ADDR0 }

shape MyFile(
    *h: void
)

shape Wrapper(val: i32)

impl MyFile@Encap {
    pub h

    fn drop(self#) {}
}

impl MyFile {
pub fn clone(self) -> MyFile {
        return MyFile(*h=self.*h)
    }
}

impl MyFile {
    fn test(self) -> Result<Wrapper, Wrapper> {
        auto *p = self.*h 
        return Result<Wrapper, Wrapper>::Ok(Wrapper(val=0))
    }
}

fn main() -> i32 {
    return 0
}
