import std/sync::{Mutex, Once}
import std/thread::{thread_spawn, yield_now}
import std/io::{println}

shape SharedData(
    counter: i32
)

pub fn main() -> i32 {
    auto init_val = SharedData(counter = 0)
    auto ~state = Mutex<SharedData>::make_shared(cede init_val)
    auto ~once# = Once::make_shared()

    auto ~state1 = ~state
    auto ~state2 = ~state
    auto ~state3 = ~state
    auto ~once1# = ~once
    auto ~once2# = ~once
    auto ~once3# = ~once
    auto task1 = { [cede ~once1, cede ~state1] =>
        auto ~local_state = ~state1
        auto ~local_once# = ~once1
        auto init# = { =>
            auto lock = local_state.lock().unwrap()
            auto &val# = lock.borrow_mut()
            val.counter = val.counter + 1
            println("init_fn executed!")
        }:fn#()
        local_once#.call(init#)
        return 0
    }:dyn fn() -> i32
    auto task2 = { [cede ~once2, cede ~state2] =>
        auto ~local_state = ~state2
        auto ~local_once# = ~once2
        auto init# = { =>
            auto lock = local_state.lock().unwrap()
            auto &val# = lock.borrow_mut()
            val.counter = val.counter + 1
            println("init_fn executed!")
        }:fn#()
        local_once#.call(init#)
        return 0
    }:dyn fn() -> i32
    auto task3 = { [cede ~once3, cede ~state3] =>
        auto ~local_state = ~state3
        auto ~local_once# = ~once3
        auto init# = { =>
            auto lock = local_state.lock().unwrap()
            auto &val# = lock.borrow_mut()
            val.counter = val.counter + 1
            println("init_fn executed!")
        }:fn#()
        local_once#.call(init#)
        return 0
    }:dyn fn() -> i32
    
    auto created1 = thread_spawn<i32>(cede task1)
    auto created2 = thread_spawn<i32>(cede task2)
    auto created3 = thread_spawn<i32>(cede task3)
    auto t1# = created1.unwrap()
    auto t2# = created2.unwrap()
    auto t3# = created3.unwrap()
    
    t1#.join().unwrap()
    t2#.join().unwrap()
    t3#.join().unwrap()
    
    auto lock = state.lock().unwrap()
    auto &val = lock.borrow_mut()
    println("Once counter value: {}", val.counter)
    assert(val.counter == 1, "Expected counter to be 1")
    
    println("Once test passed!")
    return 0
}
