import std/sync::{Mutex, MutexLock}
import std/io::println
import core/result::{Result}
import std/error::{Error}

fn main() -> i32 {
    auto m# = Mutex<i32>::new(0)
    
    // First lock
    {
        auto g = m#.lock().unwrap()
        auto &p# = g.borrow_mut()
        p = 10
        println("val: {}", p)
    }
    
    // Test mutability directly
    {
        auto g = m#.lock().unwrap()
        auto &p2 = g.borrow_mut()
        println("final val: {}", p2)
    }
    
    return 0
}
