import std/task::{sleep_async, block_on}

shape AsyncCounter(value: i32)

fn run_callable() -> async i32 {
    auto state# = AsyncCounter(value = 40)
    auto callback#: fn#(i32) -> i32 = { [cede state] value =>
        state.value = state.value + value
        state.value
    }

    sleep_async(1).await
    return callback#(2)
}

fn main() -> i32 {
    auto task = run_callable().start
    if block_on<i32>(task) != 42 {
        return 1
    }
    return 0
}
