import std/sync::{Mutex, MutexLock}
import std/io::println
import core/result::{Result}
import std/error::{Error}

fn main() -> i32 {
    auto m# = Mutex<i32>::new(42)
    
    {
        auto g = m#.lock().unwrap()
        println("Locked")
        auto &p# = g.borrow_mut()
        println("Data is {}", p)
        p = 100
        println("Modified to {}", p)
    }
    
    println("Before second lock")
    auto g = m#.lock().unwrap()
    auto &p2# = g.borrow_mut()
    println("Second lock data is {}", p2)
    if p2 == 100 {
        println("Value persisted!")
    } else {
        return 2
    }
    return 0
}
