import std/sync::{Mutex, Once}
import std/thread::{thread_spawn, yield_now}
import std/io::{println}

shape SharedData(
    counter: i32
)

pub fn main() -> i32 {
    auto init_val = SharedData(counter = 0)
    auto ~state = Mutex<SharedData>::make(init_val)
    auto ~once# = Once::make()

    auto ~state1 = ~state
    auto ~state2 = ~state
    auto ~state3 = ~state
    auto ~once1# = ~once
    auto ~once2# = ~once
    auto ~once3# = ~once
    auto init1# = { [cede state1] =>
        auto ~local_state = ~state1
        auto lock = local_state.lock().unwrap()
        auto *val# = lock.get_ref()
        val.counter = val.counter + 1
        println("init_fn executed!")
    }:fn#()
    auto init2# = { [cede state2] =>
        auto ~local_state = ~state2
        auto lock = local_state.lock().unwrap()
        auto *val# = lock.get_ref()
        val.counter = val.counter + 1
        println("init_fn executed!")
    }:fn#()
    auto init3# = { [cede state3] =>
        auto ~local_state = ~state3
        auto lock = local_state.lock().unwrap()
        auto *val# = lock.get_ref()
        val.counter = val.counter + 1
        println("init_fn executed!")
    }:fn#()
    auto task1# = { [cede once1, cede init1] =>
        auto ~local_once# = ~once1
        local_once#.call(init1)
        return cede 0
    }:fn#() -> cede i32
    auto task2# = { [cede once2, cede init2] =>
        auto ~local_once# = ~once2
        local_once#.call(init2)
        return cede 0
    }:fn#() -> cede i32
    auto task3# = { [cede once3, cede init3] =>
        auto ~local_once# = ~once3
        local_once#.call(init3)
        return cede 0
    }:fn#() -> cede i32
    
    auto t1# = thread_spawn<i32>(cede task1)
    auto t2# = thread_spawn<i32>(cede task2)
    auto t3# = thread_spawn<i32>(cede task3)
    
    t1#.join().unwrap()
    t2#.join().unwrap()
    t3#.join().unwrap()
    
    auto lock = state.lock().unwrap()
    auto *val = lock.get_ref()
    println("Once counter value: {}", val.counter)
    assert(val.counter == 1, "Expected counter to be 1")
    
    println("Once test passed!")
    return 0
}
