import std/io::{File, @Reader}
import stdx/io/bufio::{BufferedReader}
import sys/libc::{libc_remove}

shape ReaderWrapper<'R: @Reader>(
    reader#: BufferedReader<'R>
)

impl<'R: @Reader> ReaderWrapper<'R> {
    pub fn new(reader: cede 'R) -> ReaderWrapper<'R> {
        return ReaderWrapper<'R>(reader = BufferedReader<'R>::new(cede reader))
    }
}

fn main() -> i32 {
    auto path = string::from("/tmp/toka_generic_reader_bound.tmp")
    {
        auto file# = File::open(path, "w+")
        auto wrapper = ReaderWrapper<File>::new(cede file#.take())
    }
    unsafe { libc_remove(path.c_str()) }
    return 0
}
