// Copyright (c) 2026 Toka Project. All rights reserved.
// tests/pass/task_group_test.tk
// Unit test for Toka's Structured Concurrency (TaskGroup)

import std/io::{println}
import std/task::{TaskGroup, spawn_task, get_handle_addr, sleep_async, block_on, detach_forget}
import core/task::{TaskHandle}

extern fn __builtin_coro_suspend()

auto g_worker_finished# = false

extern fn __builtin_coro_current_handle() -> *void

fn worker_task() -> async i32 {
    println("Worker started!")
    auto *self_handle = __builtin_coro_current_handle()
    println("worker_task self_handle: {}", *self_handle as usize)
    unsafe {
        __builtin_coro_suspend()
    }
    println("Worker finished!")
    g_worker_finished = true
    return 0
}

fn main_task() -> async i32 {
    println("main_task started")
    auto group# = TaskGroup::new()
    
    auto h# = worker_task().start
    println("worker_task handle address: {}", get_handle_addr<i32>(h))
    spawn_task<i32>(group, h)
    
    sleep_async(50).await
    
    println("Cancelling group...")
    group#.cancel_all()
    detach_forget<i32>(h)
    
    sleep_async(100).await
    
    assert(!g_worker_finished, "Worker must not finish after group cancellation")
    println("Success! Scoped task was successfully cancelled and permanently deregistered.")
    return 0
}

pub fn main() -> i32 {
    auto main_h# = main_task().start
    println("main_task handle address: {}", get_handle_addr<i32>(main_h))
    block_on<i32>(main_h)
    return 0
}
