import core/traits::{@Encap}
auto drops# = 0:i32
shape Resource(id: i32)
impl Resource@Encap {
    pub id
    fn drop(self#) { drops += self.id }
}
shape Event(Both(^Resource, ~Resource) | Empty)
fn main() -> i32 {
    {
        auto ^unique = new Resource(id = 1)
        auto ~shared = new Resource(id = 2)
        auto ~other = ~shared
        {
            auto event = Event::Both(cede ^unique, cede ~shared)
            if drops != 0:i32 { return 1 }
        }
        if drops != 1:i32 || other.id != 2:i32 { return 2 }
    }
    if drops != 3:i32 { return 3 }
    return 0
}
